Repository backtick-se/cowait, pull requests merged in 2020-09, with the labels that each got.

#174 Cast all environment values to strings
  cowait/engine/cluster.py
  cowait/tasks/definition.py
Labels: bug

#176 Apply nest_asyncio patch for all tasks
  cowait/exec.py
  cowait/test/test_task.py
Labels: bug, enhancement

#178 Build CLI Args: Quiet & Image name
  bin/cowait
  cowait/cli/commands/build.py
  cowait/cli/task_image.py
Labels: enhancement

#181 nlp text classification example with imdb dataset
  examples/10-imdb/cowait.yml
  examples/10-imdb/imdb.py
  examples/10-imdb/requirements.txt
  examples/10-imdb/test_imdb.py
Labels: documentation
