Repository backtick-se/cowait, pull requests merged in 2021-02, with the labels that each got.

#255 Basic pdoc init for html and md
  .gitignore
  README.md
  poetry.lock
  pyproject.toml
Labels: devops, discussion, documentation

#261 Fix unhandled exception from ping on closed websocket
  cowait/network/server.py
Labels: bug

#262 Break stats sending loop on closed upstream connection
  cowait/worker/worker_node.py
Labels: bug

#264 Lost tasks properly cause errors
  cowait/network/server.py
  cowait/tasks/agent/tasklist.py
  cowait/version.py
  pyproject.toml
Labels: bug

#265 Properly merge dictionary CLI args with context configuration
  cowait/cli/commands/run.py
  cowait/cli/settings_dict.py
Labels: bug

#269 Reduce base image bloat
  .dockerignore
  .gitignore
  Dockerfile
  cowait/cli/commands/build.py
  cowait/cli/task_image.py
  cowait/types/__init__.py
  examples/06-tensorflow/requirements.txt
  examples/10-imdb/requirements.txt
  examples/10-imdb/test_imdb.py
  poetry.lock
  pyproject.toml
  pytest.ini
  setup.py
  test/types/test_numpy.py
Labels: docker, enhancement

#252 Log command & Engine cleanup
  cowait/cli/app/root.py
  cowait/cli/app/task.py
  cowait/cli/commands/__init__.py
  cowait/cli/commands/run.py
  cowait/cli/commands/task.py
  cowait/cli/commands/test.py
  cowait/engine/cluster.py
  cowait/engine/docker/docker.py
  cowait/engine/docker/utils.py
  cowait/engine/kubernetes/kubernetes.py
  cowait/engine/kubernetes/pod.py
  cowait/engine/kubernetes/utils.py
  cowait/engine/utils.py
  cowait/tasks/remote_task.py
  test/engine/docker/test_docker.py
  test/engine/docker/test_docker_util.py
Labels: cli, enhancement, feature
