Repository backtick-se/cowait, pull requests merged in 2021-05, with the labels that each got.

#309 Fix RPC call race condition
  cowait/network/rpc_client.py
Labels: bug

#312 Add resource limit arguments to cowait test
  cowait/cli/app/task.py
  cowait/cli/commands/test.py
Labels: cli

#296 Docs content
  docs/contributing.md
  docs/core-concepts/engines.md
  docs/core-concepts/everything-is-a-task.md
  docs/core-concepts/no-scheduler.md
  docs/core-concepts/overview.md
  docs/core-concepts/task-hierarchy.md
  docs/extras/dashboard.md
  docs/extras/dask.md
  docs/extras/databricks.md
  docs/extras/notebook-integration.md
  docs/extras/spark.md
  docs/get-started/asyncio.md
  docs/get-started/building-and-pushing.md
  docs/get-started/dashboard.md
  docs/get-started/dependencies.md
  docs/get-started/first-steps.md
  docs/get-started/installation.md
  docs/get-started/next-steps.md
  docs/get-started/tests.md
  docs/images/dashboard_hello_task.png
  docs/images/dashboard_overview.png
  docs/images/parallel_tasks_docker.svg
  docs/kubernetes/cluster-management.md
  docs/kubernetes/pushing-and-running.md
  docs/kubernetes/routing.md
  docs/kubernetes/setup.md
  docs/kubernetes/testing.md
  docs/quick-start.md
  docs/setup/configuration.md
  docs/setup/custom-dockerfile.md
  docs/tasks/built-in-tasks.md
  docs/tasks/custom-dockerfile.md
  docs/tasks/remote-procedure-calls.md
  docs/tasks/task-lifecycle-methods.md
  docs/tasks/type-system.md
  docs/why-cowait.md
Labels: documentation, enhancement, onboarding
